// Item name mapping — Minecraft ID → human-readable
// Covers every item that appears on DonutSMP auctions/transactions
const ITEM_NAMES = {
  // Blocks
  'minecraft:stone': 'Stone',
  'minecraft:granite': 'Granite',
  'minecraft:polished_granite': 'Polished Granite',
  'minecraft:diorite': 'Diorite',
  'minecraft:polished_diorite': 'Polished Diorite',
  'minecraft:andesite': 'Andesite',
  'minecraft:polished_andesite': 'Polished Andesite',
  'minecraft:grass_block': 'Grass Block',
  'minecraft:dirt': 'Dirt',
  'minecraft:coarse_dirt': 'Coarse Dirt',
  'minecraft:podzol': 'Podzol',
  'minecraft:cobblestone': 'Cobblestone',
  'minecraft:oak_planks': 'Oak Planks',
  'minecraft:spruce_planks': 'Spruce Planks',
  'minecraft:birch_planks': 'Birch Planks',
  'minecraft:jungle_planks': 'Jungle Planks',
  'minecraft:acacia_planks': 'Acacia Planks',
  'minecraft:dark_oak_planks': 'Dark Oak Planks',
  'minecraft:mangrove_planks': 'Mangrove Planks',
  'minecraft:cherry_planks': 'Cherry Planks',
  'minecraft:bamboo_planks': 'Bamboo Planks',
  'minecraft:crimson_planks': 'Crimson Planks',
  'minecraft:warped_planks': 'Warped Planks',
  'minecraft:bamboo_mosaic': 'Bamboo Mosaic',
  'minecraft:oak_log': 'Oak Log',
  'minecraft:spruce_log': 'Spruce Log',
  'minecraft:birch_log': 'Birch Log',
  'minecraft:jungle_log': 'Jungle Log',
  'minecraft:acacia_log': 'Acacia Log',
  'minecraft:dark_oak_log': 'Dark Oak Log',
  'minecraft:mangrove_log': 'Mangrove Log',
  'minecraft:cherry_log': 'Cherry Log',
  'minecraft:crimson_stem': 'Crimson Stem',
  'minecraft:warped_stem': 'Warped Stem',
  'minecraft:oak_wood': 'Oak Wood',
  'minecraft:spruce_wood': 'Spruce Wood',
  'minecraft:birch_wood': 'Birch Wood',
  'minecraft:jungle_wood': 'Jungle Wood',
  'minecraft:acacia_wood': 'Acacia Wood',
  'minecraft:dark_oak_wood': 'Dark Oak Wood',
  'minecraft:mangrove_wood': 'Mangrove Wood',
  'minecraft:cherry_wood': 'Cherry Wood',
  'minecraft:crimson_hyphae': 'Crimson Hyphae',
  'minecraft:warped_hyphae': 'Warped Hyphae',
  'minecraft:stripped_oak_log': 'Stripped Oak Log',
  'minecraft:stripped_spruce_log': 'Stripped Spruce Log',
  'minecraft:stripped_birch_log': 'Stripped Birch Log',
  'minecraft:stripped_jungle_log': 'Stripped Jungle Log',
  'minecraft:stripped_acacia_log': 'Stripped Acacia Log',
  'minecraft:stripped_dark_oak_log': 'Stripped Dark Oak Log',
  'minecraft:stripped_mangrove_log': 'Stripped Mangrove Log',
  'minecraft:stripped_cherry_log': 'Stripped Cherry Log',
  'minecraft:stripped_crimson_stem': 'Stripped Crimson Stem',
  'minecraft:stripped_warped_stem': 'Stripped Warped Stem',
  'minecraft:stripped_oak_wood': 'Stripped Oak Wood',
  'minecraft:stripped_spruce_wood': 'Stripped Spruce Wood',
  'minecraft:stripped_birch_wood': 'Stripped Birch Wood',
  'minecraft:stripped_jungle_wood': 'Stripped Jungle Wood',
  'minecraft:stripped_acacia_wood': 'Stripped Acacia Wood',
  'minecraft:stripped_dark_oak_wood': 'Stripped Dark Oak Wood',
  'minecraft:stripped_mangrove_wood': 'Stripped Mangrove Wood',
  'minecraft:stripped_cherry_wood': 'Stripped Cherry Wood',
  'minecraft:stripped_crimson_hyphae': 'Stripped Crimson Hyphae',
  'minecraft:stripped_warped_hyphae': 'Stripped Warped Hyphae',
  'minecraft:oak_slab': 'Oak Slab',
  'minecraft:spruce_slab': 'Spruce Slab',
  'minecraft:birch_slab': 'Birch Slab',
  'minecraft:jungle_slab': 'Jungle Slab',
  'minecraft:acacia_slab': 'Acacia Slab',
  'minecraft:dark_oak_slab': 'Dark Oak Slab',
  'minecraft:mangrove_slab': 'Mangrove Slab',
  'minecraft:cherry_slab': 'Cherry Slab',
  'minecraft:bamboo_slab': 'Bamboo Slab',
  'minecraft:crimson_slab': 'Crimson Slab',
  'minecraft:warped_slab': 'Warped Slab',
  'minecraft:bamboo_mosaic_slab': 'Bamboo Mosaic Slab',
  'minecraft:bookshelf': 'Bookshelf',
  'minecraft:chiseled_nether_bricks': 'Chiseled Nether Bricks',
  'minecraft:cracked_nether_bricks': 'Cracked Nether Bricks',
  'minecraft:quartz_block': 'Quartz Block',
  'minecraft:chiseled_quartz_block': 'Chiseled Quartz Block',
  'minecraft:quartz_pillar': 'Quartz Pillar',
  'minecraft:smooth_quartz': 'Smooth Quartz',
  'minecraft:smooth_stone': 'Smooth Stone',
  'minecraft:stone_bricks': 'Stone Bricks',
  'minecraft:cracked_stone_bricks': 'Cracked Stone Bricks',
  'minecraft:mossy_stone_bricks': 'Mossy Stone Bricks',
  'minecraft:chiseled_stone_bricks': 'Chiseled Stone Bricks',
  'minecraft:infested_stone': 'Infested Stone',
  'minecraft:infested_cobblestone': 'Infested Cobblestone',
  'minecraft:infested_stone_bricks': 'Infested Stone Bricks',
  'minecraft:infested_mossy_stone_bricks': 'Infested Mossy Stone Bricks',
  'minecraft:infested_cracked_stone_bricks': 'Infested Cracked Stone Bricks',
  'minecraft:infested_chiseled_stone_bricks': 'Infested Chiseled Stone Bricks',
  'minecraft:deepslate': 'Deepslate',
  'minecraft:cobbled_deepslate': 'Cobbled Deepslate',
  'minecraft:polished_deepslate': 'Polished Deepslate',
  'minecraft:deepslate_bricks': 'Deepslate Bricks',
  'minecraft:cracked_deepslate_bricks': 'Cracked Deepslate Bricks',
  'minecraft:deepslate_tiles': 'Deepslate Tiles',
  'minecraft:cracked_deepslate_tiles': 'Cracked Deepslate Tiles',
  'minecraft:chiseled_deepslate': 'Chiseled Deepslate',
  'minecraft:mossy_cobblestone': 'Mossy Cobblestone',
  'minecraft:smooth_sandstone': 'Smooth Sandstone',
  'minecraft:chiseled_sandstone': 'Chiseled Sandstone',
  'minecraft:cut_sandstone': 'Cut Sandstone',
  'minecraft:smooth_red_sandstone': 'Smooth Red Sandstone',
  'minecraft:chiseled_red_sandstone': 'Chiseled Red Sandstone',
  'minecraft:cut_red_sandstone': 'Cut Red Sandstone',
  'minecraft:slime_block': 'Slime Block',
  'minecraft:honey_block': 'Honey Block',
  'minecraft:honeycomb_block': 'Honeycomb Block',
  'minecraft:observer': 'Observer',
  'minecraft:piston': 'Piston',
  'minecraft:sticky_piston': 'Sticky Piston',
  'minecraft:tnt': 'TNT',
  'minecraft:dispenser': 'Dispenser',
  'minecraft:dropper': 'Dropper',
  'minecraft:note_block': 'Note Block',
  'minecraft:crafting_table': 'Crafting Table',
  'minecraft:furnace': 'Furnace',
  'minecraft:blast_furnace': 'Blast Furnace',
  'minecraft:smoker': 'Smoker',
  'minecraft:barrel': 'Barrel',
  'minecraft:cartography_table': 'Cartography Table',
  'minecraft:fletching_table': 'Fletching Table',
  'minecraft:grindstone': 'Grindstone',
  'minecraft:smithing_table': 'Smithing Table',
  'minecraft:loom': 'Loom',
  'minecraft:composter': 'Composter',
  'minecraft:stonecutter': 'Stonecutter',
  'minecraft:bell': 'Bell',
  'minecraft:campfire': 'Campfire',
  'minecraft:soul_campfire': 'Soul Campfire',
  'minecraft:lectern': 'Lectern',
  'minecraft:conduit': 'Conduit',
  'minecraft:respawn_anchor': 'Respawn Anchor',
  'minecraft:lodestone': 'Lodestone',
  'minecraft:lightning_rod': 'Lightning Rod',
  'minecraft:chain': 'Chain',
  'minecraft:flower_pot': 'Flower Pot',
  // Ores
  'minecraft:coal_ore': 'Coal Ore',
  'minecraft:deepslate_coal_ore': 'Deepslate Coal Ore',
  'minecraft:iron_ore': 'Iron Ore',
  'minecraft:deepslate_iron_ore': 'Deepslate Iron Ore',
  'minecraft:copper_ore': 'Copper Ore',
  'minecraft:deepslate_copper_ore': 'Deepslate Copper Ore',
  'minecraft:gold_ore': 'Gold Ore',
  'minecraft:deepslate_gold_ore': 'Deepslate Gold Ore',
  'minecraft:redstone_ore': 'Redstone Ore',
  'minecraft:deepslate_redstone_ore': 'Deepslate Redstone Ore',
  'minecraft:emerald_ore': 'Emerald Ore',
  'minecraft:deepslate_emerald_ore': 'Deepslate Emerald Ore',
  'minecraft:lapis_ore': 'Lapis Ore',
  'minecraft:deepslate_lapis_ore': 'Deepslate Lapis Ore',
  'minecraft:diamond_ore': 'Diamond Ore',
  'minecraft:deepslate_diamond_ore': 'Deepslate Diamond Ore',
  'minecraft:nether_gold_ore': 'Nether Gold Ore',
  'minecraft:nether_quartz_ore': 'Nether Quartz Ore',
  // Ingots & materials
  'minecraft:iron_ingot': 'Iron Ingot',
  'minecraft:gold_ingot': 'Gold Ingot',
  'minecraft:copper_ingot': 'Copper Ingot',
  'minecraft:diamond': 'Diamond',
  'minecraft:emerald': 'Emerald',
  'minecraft:lapis_lazuli': 'Lapis Lazuli',
  'minecraft:redstone': 'Redstone',
  'minecraft:coal': 'Coal',
  'minecraft:netherite_scrap': 'Netherite Scrap',
  'minecraft:netherite_ingot': 'Netherite Ingot',
  'minecraft:netherite_block': 'Block of Netherite',
  'minecraft:iron_block': 'Iron Block',
  'minecraft:gold_block': 'Gold Block',
  'minecraft:diamond_block': 'Diamond Block',
  'minecraft:emerald_block': 'Emerald Block',
  'minecraft:lapis_block': 'Lapis Block',
  'minecraft:redstone_block': 'Redstone Block',
  'minecraft:coal_block': 'Coal Block',
  'minecraft:copper_block': 'Copper Block',
  'minecraft:raw_iron_block': 'Raw Iron Block',
  'minecraft:raw_gold_block': 'Raw Gold Block',
  'minecraft:raw_copper_block': 'Raw Copper Block',
  'minecraft:amethyst_block': 'Amethyst Block',
  'minecraft:budding_amethyst': 'Budding Amethyst',
  'minecraft:smooth_stone_slab': 'Smooth Stone Slab',
  'minecraft:cobbled_deepslate_slab': 'Cobbled Deepslate Slab',
  'minecraft:polished_deepslate_slab': 'Polished Deepslate Slab',
  'minecraft:deepslate_brick_slab': 'Deepslate Brick Slab',
  'minecraft:deepslate_tile_slab': 'Deepslate Tile Slab',
  'minecraft:stone_brick_slab': 'Stone Brick Slab',
  'minecraft:mossy_stone_brick_slab': 'Mossy Stone Brick Slab',
  'minecraft:sandstone_slab': 'Sandstone Slab',
  'minecraft:cut_sandstone_slab': 'Cut Sandstone Slab',
  'minecraft:smooth_sandstone_slab': 'Smooth Sandstone Slab',
  'minecraft:chiseled_sandstone_slab': 'Chiseled Sandstone Slab',
  'minecraft:red_sandstone_slab': 'Red Sandstone Slab',
  'minecraft:cut_red_sandstone_slab': 'Cut Red Sandstone Slab',
  'minecraft:smooth_red_sandstone_slab': 'Smooth Red Sandstone Slab',
  'minecraft:chiseled_red_sandstone_slab': 'Chiseled Red Sandstone Slab',
  'minecraft:quartz_slab': 'Quartz Slab',
  'minecraft:smooth_quartz_slab': 'Smooth Quartz Slab',
  'minecraft:chiseled_quartz_slab': 'Chiseled Quartz Slab',
  'minecraft:quartz_brick_slab': 'Quartz Brick Slab',
  'minecraft:nether_brick_slab': 'Nether Brick Slab',
  'minecraft:crimson_slab': 'Crimson Slab',
  'minecraft:warped_slab': 'Warped Slab',
  'minecraft:blackstone_slab': 'Blackstone Slab',
  'minecraft:polished_blackstone_slab': 'Polished Blackstone Slab',
  'minecraft:polished_blackstone_brick_slab': 'Polished Blackstone Brick Slab',
  'minecraft:purpur_slab': 'Purpur Slab',
  'minecraft:prismarine_slab': 'Prismarine Slab',
  'minecraft:prismarine_brick_slab': 'Prismarine Brick Slab',
  'minecraft:dark_prismarine_slab': 'Dark Prismarine Slab',
  // Colored blocks
  'minecraft:white_concrete': 'White Concrete',
  'minecraft:orange_concrete': 'Orange Concrete',
  'minecraft:magenta_concrete': 'Magenta Concrete',
  'minecraft:light_blue_concrete': 'Light Blue Concrete',
  'minecraft:yellow_concrete': 'Yellow Concrete',
  'minecraft:lime_concrete': 'Lime Concrete',
  'minecraft:pink_concrete': 'Pink Concrete',
  'minecraft:gray_concrete': 'Gray Concrete',
  'minecraft:light_gray_concrete': 'Light Gray Concrete',
  'minecraft:cyan_concrete': 'Cyan Concrete',
  'minecraft:purple_concrete': 'Purple Concrete',
  'minecraft:blue_concrete': 'Blue Concrete',
  'minecraft:brown_concrete': 'Brown Concrete',
  'minecraft:green_concrete': 'Green Concrete',
  'minecraft:red_concrete': 'Red Concrete',
  'minecraft:black_concrete': 'Black Concrete',
  'minecraft:white_concrete_powder': 'White Concrete Powder',
  'minecraft:orange_concrete_powder': 'Orange Concrete Powder',
  'minecraft:magenta_concrete_powder': 'Magenta Concrete Powder',
  'minecraft:light_blue_concrete_powder': 'Light Blue Concrete Powder',
  'minecraft:yellow_concrete_powder': 'Yellow Concrete Powder',
  'minecraft:lime_concrete_powder': 'Lime Concrete Powder',
  'minecraft:pink_concrete_powder': 'Pink Concrete Powder',
  'minecraft:gray_concrete_powder': 'Gray Concrete Powder',
  'minecraft:light_gray_concrete_powder': 'Light Gray Concrete Powder',
  'minecraft:cyan_concrete_powder': 'Cyan Concrete Powder',
  'minecraft:purple_concrete_powder': 'Purple Concrete Powder',
  'minecraft:blue_concrete_powder': 'Blue Concrete Powder',
  'minecraft:brown_concrete_powder': 'Brown Concrete Powder',
  'minecraft:green_concrete_powder': 'Green Concrete Powder',
  'minecraft:red_concrete_powder': 'Red Concrete Powder',
  'minecraft:black_concrete_powder': 'Black Concrete Powder',
  'minecraft:white_wool': 'White Wool',
  'minecraft:orange_wool': 'Orange Wool',
  'minecraft:magenta_wool': 'Magenta Wool',
  'minecraft:light_blue_wool': 'Light Blue Wool',
  'minecraft:yellow_wool': 'Yellow Wool',
  'minecraft:lime_wool': 'Lime Wool',
  'minecraft:pink_wool': 'Pink Wool',
  'minecraft:gray_wool': 'Gray Wool',
  'minecraft:light_gray_wool': 'Light Gray Wool',
  'minecraft:cyan_wool': 'Cyan Wool',
  'minecraft:purple_wool': 'Purple Wool',
  'minecraft:blue_wool': 'Blue Wool',
  'minecraft:brown_wool': 'Brown Wool',
  'minecraft:green_wool': 'Green Wool',
  'minecraft:red_wool': 'Red Wool',
  'minecraft:black_wool': 'Black Wool',
  'minecraft:white_stained_glass': 'White Stained Glass',
  'minecraft:orange_stained_glass': 'Orange Stained Glass',
  'minecraft:magenta_stained_glass': 'Magenta Stained Glass',
  'minecraft:light_blue_stained_glass': 'Light Blue Stained Glass',
  'minecraft:yellow_stained_glass': 'Yellow Stained Glass',
  'minecraft:lime_stained_glass': 'Lime Stained Glass',
  'minecraft:pink_stained_glass': 'Pink Stained Glass',
  'minecraft:gray_stained_glass': 'Gray Stained Glass',
  'minecraft:light_gray_stained_glass': 'Light Gray Stained Glass',
  'minecraft:cyan_stained_glass': 'Cyan Stained Glass',
  'minecraft:purple_stained_glass': 'Purple Stained Glass',
  'minecraft:blue_stained_glass': 'Blue Stained Glass',
  'minecraft:brown_stained_glass': 'Brown Stained Glass',
  'minecraft:green_stained_glass': 'Green Stained Glass',
  'minecraft:red_stained_glass': 'Red Stained Glass',
  'minecraft:black_stained_glass': 'Black Stained Glass',
  'minecraft:white_stained_glass_pane': 'White Stained Glass Pane',
  'minecraft:light_blue_stained_glass_pane': 'Light Blue Stained Glass Pane',
  'minecraft:cyan_stained_glass_pane': 'Cyan Stained Glass Pane',
  // Dyes
  'minecraft:white_dye': 'White Dye',
  'minecraft:orange_dye': 'Orange Dye',
  'minecraft:magenta_dye': 'Magenta Dye',
  'minecraft:light_blue_dye': 'Light Blue Dye',
  'minecraft:yellow_dye': 'Yellow Dye',
  'minecraft:lime_dye': 'Lime Dye',
  'minecraft:pink_dye': 'Pink Dye',
  'minecraft:gray_dye': 'Gray Dye',
  'minecraft:light_gray_dye': 'Light Gray Dye',
  'minecraft:cyan_dye': 'Cyan Dye',
  'minecraft:purple_dye': 'Purple Dye',
  'minecraft:blue_dye': 'Blue Dye',
  'minecraft:brown_dye': 'Brown Dye',
  'minecraft:green_dye': 'Green Dye',
  'minecraft:red_dye': 'Red Dye',
  'minecraft:black_dye': 'Black Dye',
  'minecraft:cocoa_beans': 'Cocoa Beans',
  'minecraft:ink_sac': 'Ink Sac',
  // Nether
  'minecraft:netherrack': 'Netherrack',
  'minecraft:nether_bricks': 'Nether Bricks',
  'minecraft:red_nether_bricks': 'Red Nether Bricks',
  'minecraft:brown_mushroom_block': 'Brown Mushroom Block',
  'minecraft:red_mushroom_block': 'Red Mushroom Block',
  'minecraft:shroomlight': 'Shroomlight',
  'minecraft:warped_nylium': 'Warped Nylium',
  'minecraft:crimson_nylium': 'Crimson Nylium',
  'minecraft:warped_wart_block': 'Warped Wart Block',
  'minecraft:nether_wart_block': 'Nether Wart Block',
  'minecraft:basalt': 'Basalt',
  'minecraft:smooth_basalt': 'Smooth Basalt',
  'minecraft:polished_basalt': 'Polished Basalt',
  'minecraft:blackstone': 'Blackstone',
  'minecraft:polished_blackstone': 'Polished Blackstone',
  'minecraft:polished_blackstone_bricks': 'Polished Blackstone Bricks',
  'minecraft:chiseled_polished_blackstone': 'Chiseled Polished Blackstone',
  'minecraft:cracked_polished_blackstone_bricks': 'Cracked Polished Blackstone Bricks',
  'minecraft:chiseled_nether_bricks': 'Chiseled Nether Bricks',
  'minecraft:gilded_blackstone': 'Gilded Blackstone',
  'minecraft:soul_sand': 'Soul Sand',
  'minecraft:soul_soil': 'Soul Soil',
  'minecraft:magma_block': 'Magma Block',
  'minecraft:crying_obsidian': 'Crying Obsidian',
  'minecraft:obsidian': 'Obsidian',
  'minecraft:end_stone': 'End Stone',
  'minecraft:end_stone_bricks': 'End Stone Bricks',
  'minecraft:purpur_block': 'Purpur Block',
  'minecraft:purpur_pillar': 'Purpur Pillar',
  'minecraft:prismarine': 'Prismarine',
  'minecraft:prismarine_bricks': 'Prismarine Bricks',
  'minecraft:dark_prismarine': 'Dark Prismarine',
  'minecraft:sea_lantern': 'Sea Lantern',
  'minecraft:glowstone': 'Glowstone',
  'minecraft:jack_o_lantern': "Jack o'Lantern",
  'minecraft:ice': 'Ice',
  'minecraft:packed_ice': 'Packed Ice',
  'minecraft:blue_ice': 'Blue Ice',
  'minecraft:snow_block': 'Snow Block',
  'minecraft:snow': 'Snow',
  // Redstone
  'minecraft:redstone_lamp': 'Redstone Lamp',
  'minecraft:redstone_torch': 'Redstone Torch',
  'minecraft:redstone_wire': 'Redstone Wire',
  'minecraft:lever': 'Lever',
  'minecraft:stone_pressure_plate': 'Stone Pressure Plate',
  'minecraft:light_weighted_pressure_plate': 'Light Weighted Pressure Plate',
  'minecraft:heavy_weighted_pressure_plate': 'Heavy Weighted Pressure Plate',
  'minecraft:tripwire_hook': 'Tripwire Hook',
  'minecraft:trapped_chest': 'Trapped Chest',
  'minecraft:hopper': 'Hopper',
  'minecraft:comparator': 'Comparator',
  'minecraft:repeater': 'Repeater',
  'minecraft:daylight_detector': 'Daylight Detector',
  'minecraft:target': 'Target',
  'minecraft:sculk_sensor': 'Sculk Sensor',
  'minecraft:sculk_shrieker': 'Sculk Shrieker',
  'minecraft:sculk_catalyst': 'Sculk Catalyst',
  'minecraft:sculk': 'Sculk',
  // Decorations
  'minecraft:torch': 'Torch',
  'minecraft:soul_torch': 'Soul Torch',
  'minecraft:lantern': 'Lantern',
  'minecraft:soul_lantern': 'Soul Lantern',
  'minecraft:glow_lichen': 'Glow Lichen',
  'minecraft:light': 'Light',
  'minecraft:candle': 'Candle',
  'minecraft:white_candle': 'White Candle',
  'minecraft:orange_candle': 'Orange Candle',
  'minecraft:magenta_candle': 'Magenta Candle',
  'minecraft:light_blue_candle': 'Light Blue Candle',
  'minecraft:yellow_candle': 'Yellow Candle',
  'minecraft:lime_candle': 'Lime Candle',
  'minecraft:pink_candle': 'Pink Candle',
  'minecraft:gray_candle': 'Gray Candle',
  'minecraft:light_gray_candle': 'Light Gray Candle',
  'minecraft:cyan_candle': 'Cyan Candle',
  'minecraft:purple_candle': 'Purple Candle',
  'minecraft:blue_candle': 'Blue Candle',
  'minecraft:brown_candle': 'Brown Candle',
  'minecraft:green_candle': 'Green Candle',
  'minecraft:red_candle': 'Red Candle',
  'minecraft:black_candle': 'Black Candle',
  // Potions
  'minecraft:potion': 'Potion',
  'minecraft:splash_potion': 'Splash Potion',
  'minecraft:lingering_potion': 'Lingering Potion',
  'minecraft:glass_bottle': 'Glass Bottle',
  'minecraft:experience_bottle': 'Experience Bottle',
  'minecraft:dragon_breath': 'Dragon Breath',
  // Tools
  'minecraft:wooden_sword': 'Wooden Sword',
  'minecraft:wooden_pickaxe': 'Wooden Pickaxe',
  'minecraft:wooden_axe': 'Wooden Axe',
  'minecraft:wooden_shovel': 'Wooden Shovel',
  'minecraft:wooden_hoe': 'Wooden Hoe',
  'minecraft:stone_sword': 'Stone Sword',
  'minecraft:stone_pickaxe': 'Stone Pickaxe',
  'minecraft:stone_axe': 'Stone Axe',
  'minecraft:stone_shovel': 'Stone Shovel',
  'minecraft:stone_hoe': 'Stone Hoe',
  'minecraft:iron_sword': 'Iron Sword',
  'minecraft:iron_pickaxe': 'Iron Pickaxe',
  'minecraft:iron_axe': 'Iron Axe',
  'minecraft:iron_shovel': 'Iron Shovel',
  'minecraft:iron_hoe': 'Iron Hoe',
  'minecraft:diamond_sword': 'Diamond Sword',
  'minecraft:diamond_pickaxe': 'Diamond Pickaxe',
  'minecraft:diamond_axe': 'Diamond Axe',
  'minecraft:diamond_shovel': 'Diamond Shovel',
  'minecraft:diamond_hoe': 'Diamond Hoe',
  'minecraft:netherite_sword': 'Netherite Sword',
  'minecraft:netherite_pickaxe': 'Netherite Pickaxe',
  'minecraft:netherite_axe': 'Netherite Axe',
  'minecraft:netherite_shovel': 'Netherite Shovel',
  'minecraft:netherite_hoe': 'Netherite Hoe',
  'minecraft:golden_sword': 'Golden Sword',
  'minecraft:golden_pickaxe': 'Golden Pickaxe',
  'minecraft:golden_axe': 'Golden Axe',
  'minecraft:golden_shovel': 'Golden Shovel',
  'minecraft:golden_hoe': 'Golden Hoe',
  'minecraft:bow': 'Bow',
  'minecraft:crossbow': 'Crossbow',
  'minecraft:fishing_rod': 'Fishing Rod',
  'minecraft:flint_and_steel': 'Flint and Steel',
  'minecraft:shears': 'Shears',
  'minecraft:brush': 'Brush',
  'minecraft:trident': 'Trident',
  'minecraft:mace': 'Mace',
  'minecraft:spyglass': 'Spyglass',
  // Armor
  'minecraft:leather_helmet': 'Leather Helmet',
  'minecraft:leather_chestplate': 'Leather Chestplate',
  'minecraft:leather_leggings': 'Leather Leggings',
  'minecraft:leather_boots': 'Leather Boots',
  'minecraft:chainmail_helmet': 'Chainmail Helmet',
  'minecraft:chainmail_chestplate': 'Chainmail Chestplate',
  'minecraft:chainmail_leggings': 'Chainmail Leggings',
  'minecraft:chainmail_boots': 'Chainmail Boots',
  'minecraft:iron_helmet': 'Iron Helmet',
  'minecraft:iron_chestplate': 'Iron Chestplate',
  'minecraft:iron_leggings': 'Iron Leggings',
  'minecraft:iron_boots': 'Iron Boots',
  'minecraft:diamond_helmet': 'Diamond Helmet',
  'minecraft:diamond_chestplate': 'Diamond Chestplate',
  'minecraft:diamond_leggings': 'Diamond Leggings',
  'minecraft:diamond_boots': 'Diamond Boots',
  'minecraft:netherite_helmet': 'Netherite Helmet',
  'minecraft:netherite_chestplate': 'Netherite Chestplate',
  'minecraft:netherite_leggings': 'Netherite Leggings',
  'minecraft:netherite_boots': 'Netherite Boots',
  'minecraft:golden_helmet': 'Golden Helmet',
  'minecraft:golden_chestplate': 'Golden Chestplate',
  'minecraft:golden_leggings': 'Golden Leggings',
  'minecraft:golden_boots': 'Golden Boots',
  'minecraft:turtle_helmet': 'Turtle Helmet',
  'minecraft:shield': 'Shield',
  // Food
  'minecraft:apple': 'Apple',
  'minecraft:golden_apple': 'Golden Apple',
  'minecraft:enchanted_golden_apple': 'Enchanted Golden Apple',
  'minecraft:bread': 'Bread',
  'minecraft:wheat': 'Wheat',
  'minecraft:carrot': 'Carrot',
  'minecraft:golden_carrot': 'Golden Carrot',
  'minecraft:potato': 'Potato',
  'minecraft:baked_potato': 'Baked Potato',
  'minecraft:cooked_beef': 'Cooked Beef',
  'minecraft:beef': 'Beef',
  'minecraft:cooked_porkchop': 'Cooked Porkchop',
  'minecraft:porkchop': 'Porkchop',
  'minecraft:cooked_mutton': 'Cooked Mutton',
  'minecraft:mutton': 'Mutton',
  'minecraft:cooked_chicken': 'Cooked Chicken',
  'minecraft:chicken': 'Chicken',
  'minecraft:cooked_rabbit': 'Cooked Rabbit',
  'minecraft:rabbit': 'Rabbit',
  'minecraft:cooked_cod': 'Cooked Cod',
  'minecraft:cod': 'Cod',
  'minecraft:cooked_salmon': 'Cooked Salmon',
  'minecraft:salmon': 'Salmon',
  'minecraft:cookie': 'Cookie',
  'minecraft:cake': 'Cake',
  'minecraft:pumpkin_pie': 'Pumpkin Pie',
  'minecraft:mushroom_stew': 'Mushroom Stew',
  'minecraft:beetroot_soup': 'Beetroot Soup',
  'minecraft:rabbit_stew': 'Rabbit Stew',
  'minecraft:dried_kelp': 'Dried Kelp',
  'minecraft:dried_kelp_block': 'Dried Kelp Block',
  'minecraft:sugar_cane': 'Sugar Cane',
  'minecraft:pumpkin': 'Pumpkin',
  'minecraft:melon_slice': 'Melon Slice',
  'minecraft:melon': 'Melon',
  'minecraft:sweet_berries': 'Sweet Berries',
  'minecraft:glow_berries': 'Glow Berries',
  'minecraft:beetroot': 'Beetroot',
  'minecraft:beetroot_seeds': 'Beetroot Seeds',
  'minecraft:melon_seeds': 'Melon Seeds',
  'minecraft:pumpkin_seeds': 'Pumpkin Seeds',
  'minecraft:torchflower_seeds': 'Torchflower Seeds',
  'minecraft:pitcher_plant': 'Pitcher Plant',
  'minecraft:sea_pickle': 'Sea Pickle',
  'minecraft:cactus': 'Cactus',
  'minecraft:bamboo': 'Bamboo',
  // Mobs & items
  'minecraft:ender_pearl': 'Ender Pearl',
  'minecraft:blaze_rod': 'Blaze Rod',
  'minecraft:blaze_powder': 'Blaze Powder',
  'minecraft:ghast_tear': 'Ghast Tear',
  'minecraft:magma_cream': 'Magma Cream',
  'minecraft:ender_eye': 'Eye of Ender',
  'minecraft:fermented_spider_eye': 'Fermented Spider Eye',
  'minecraft:spider_eye': 'Spider Eye',
  'minecraft:slime_ball': 'Slime Ball',
  'minecraft:string': 'String',
  'minecraft:feather': 'Feather',
  'minecraft:flint': 'Flint',
  'minecraft:gunpowder': 'Gunpowder',
  'minecraft:bone': 'Bone',
  'minecraft:bone_meal': 'Bone Meal',
  'minecraft:leather': 'Leather',
  'minecraft:egg': 'Egg',
  'minecraft:clay_ball': 'Clay Ball',
  'minecraft:paper': 'Paper',
  'minecraft:book': 'Book',
  'minecraft:written_book': 'Written Book',
  'minecraft:quill': 'Quill',
  'minecraft:map': 'Map',
  'minecraft:filled_map': 'Filled Map',
  'minecraft:compass': 'Compass',
  'minecraft:recovery_compass': 'Recovery Compass',
  'minecraft:clock': 'Clock',
  'minecraft:firework_rocket': 'Firework Rocket',
  'minecraft:firework_star': 'Firework Star',
  'minecraft:lead': 'Lead',
  'minecraft:name_tag': 'Name Tag',
  'minecraft:saddle': 'Saddle',
  'minecraft:totem_of_undying': 'Totem of Undying',
  'minecraft:shulker_shell': 'Shulker Shell',
  'minecraft:nether_star': 'Nether Star',
  'minecraft:dragon_egg': 'Dragon Egg',
  'minecraft:prismarine_crystals': 'Prismarine Crystals',
  'minecraft:prismarine_shard': 'Prismarine Shard',
  'minecraft:nautilus_shell': 'Nautilus Shell',
  'minecraft:heart_of_the_sea': 'Heart of the Sea',
  'minecraft:popped_chorus_fruit': 'Popped Chorus Fruit',
  'minecraft:chorus_fruit': 'Chorus Fruit',
  'minecraft:end_rod': 'End Rod',
  'minecraft:dragon_breath': 'Dragon Breath',
  'minecraft:elytra': 'Elytra',
  'minecraft:turtle_egg': 'Turtle Egg',
  'minecraft:scute': 'Scute',
  'minecraft:sniffer_egg': 'Sniffer Egg',
  'minecraft:armadillo_scute': 'Armadillo Scute',
  'minecraft:torchflower': 'Torchflower',
  'minecraft:pitcher_plant': 'Pitcher Plant',
  'minecraft:large_fern': 'Large Fern',
  // Shulker boxes
  'minecraft:shulker_box': 'Shulker Box',
  'minecraft:white_shulker_box': 'White Shulker Box',
  'minecraft:orange_shulker_box': 'Orange Shulker Box',
  'minecraft:magenta_shulker_box': 'Magenta Shulker Box',
  'minecraft:light_blue_shulker_box': 'Light Blue Shulker Box',
  'minecraft:yellow_shulker_box': 'Yellow Shulker Box',
  'minecraft:lime_shulker_box': 'Lime Shulker Box',
  'minecraft:pink_shulker_box': 'Pink Shulker Box',
  'minecraft:gray_shulker_box': 'Gray Shulker Box',
  'minecraft:light_gray_shulker_box': 'Light Gray Shulker Box',
  'minecraft:cyan_shulker_box': 'Cyan Shulker Box',
  'minecraft:purple_shulker_box': 'Purple Shulker Box',
  'minecraft:blue_shulker_box': 'Blue Shulker Box',
  'minecraft:brown_shulker_box': 'Brown Shulker Box',
  'minecraft:green_shulker_box': 'Green Shulker Box',
  'minecraft:red_shulker_box': 'Red Shulker Box',
  'minecraft:black_shulker_box': 'Black Shulker Box',
  // Misc blocks
  'minecraft:crafting_table': 'Crafting Table',
  'minecraft:enchanting_table': 'Enchanting Table',
  'minecraft:end_portal_frame': 'End Portal Frame',
  'minecraft:end_portal': 'End Portal',
  'minecraft:dragon_head': 'Dragon Head',
  'minecraft:creeper_head': 'Creeper Head',
  'minecraft:skeleton_skull': 'Skeleton Skull',
  'minecraft:wither_skeleton_skull': 'Wither Skeleton Skull',
  'minecraft:zombie_head': 'Zombie Head',
  'minecraft:piglin_head': 'Piglin Head',
  'minecraft:piglin_banner_pattern': 'Piglin Banner Pattern',
  'minecraft:ominous_bottle': 'Ominous Bottle',
  'minecraft:ominous_trial_key': 'Ominous Trial Key',
  'minecraft:trial_key': 'Trial Key',
  'minecraft:wind_charge': 'Wind Charge',
  'minecraft:heavy_core': 'Heavy Core',
  'minecraft:breeze_rod': 'Breeze Rod',
  'minecraft:goat_horn': 'Goat Horn',
  'minecraft:amethyst_shard': 'Amethyst Shard',
  'minecraft:raw_iron': 'Raw Iron',
  'minecraft:raw_gold': 'Raw Gold',
  'minecraft:raw_copper': 'Raw Copper',
  'minecraft:glow_ink_sac': 'Glow Ink Sac',
  'minecraft:honeycomb': 'Honeycomb',
  'minecraft:honey_bottle': 'Honey Bottle',
  'minecraft:ender_pearl': 'Ender Pearl',
  'minecraft:suspicious_sand': 'Suspicious Sand',
  'minecraft:suspicious_gravel': 'Suspicious Gravel',
  'minecraft:brush': 'Brush',
  // Spawn eggs & special
  'minecraft:axolotl_bucket': 'Axolotl Bucket',
  'minecraft:tropical_fish_bucket': 'Tropical Fish Bucket',
  'minecraft:pufferfish_bucket': 'Pufferfish Bucket',
  'minecraft:salmon_bucket': 'Salmon Bucket',
  'minecraft:cod_bucket': 'Cod Bucket',
  'minecraft:water_bucket': 'Water Bucket',
  'minecraft:lava_bucket': 'Lava Bucket',
  'minecraft:milk_bucket': 'Milk Bucket',
  'minecraft:powder_snow_bucket': 'Powder Snow Bucket',
  // Anvils
  'minecraft:anvil': 'Anvil',
  'minecraft:chipped_anvil': 'Chipped Anvil',
  'minecraft:damaged_anvil': 'Damaged Anvil',
  // Carpets
  'minecraft:white_carpet': 'White Carpet',
  'minecraft:orange_carpet': 'Orange Carpet',
  'minecraft:magenta_carpet': 'Magenta Carpet',
  'minecraft:light_blue_carpet': 'Light Blue Carpet',
  'minecraft:yellow_carpet': 'Yellow Carpet',
  'minecraft:lime_carpet': 'Lime Carpet',
  'minecraft:pink_carpet': 'Pink Carpet',
  'minecraft:gray_carpet': 'Gray Carpet',
  'minecraft:light_gray_carpet': 'Light Gray Carpet',
  'minecraft:cyan_carpet': 'Cyan Carpet',
  'minecraft:purple_carpet': 'Purple Carpet',
  'minecraft:blue_carpet': 'Blue Carpet',
  'minecraft:brown_carpet': 'Brown Carpet',
  'minecraft:green_carpet': 'Green Carpet',
  'minecraft:red_carpet': 'Red Carpet',
  'minecraft:black_carpet': 'Black Carpet',
  // Beds
  'minecraft:white_bed': 'White Bed',
  'minecraft:orange_bed': 'Orange Bed',
  'minecraft:magenta_bed': 'Magenta Bed',
  'minecraft:light_blue_bed': 'Light Blue Bed',
  'minecraft:yellow_bed': 'Yellow Bed',
  'minecraft:lime_bed': 'Lime Bed',
  'minecraft:pink_bed': 'Pink Bed',
  'minecraft:gray_bed': 'Gray Bed',
  'minecraft:light_gray_bed': 'Light Gray Bed',
  'minecraft:cyan_bed': 'Cyan Bed',
  'minecraft:purple_bed': 'Purple Bed',
  'minecraft:blue_bed': 'Blue Bed',
  'minecraft:brown_bed': 'Brown Bed',
  'minecraft:green_bed': 'Green Bed',
  'minecraft:red_bed': 'Red Bed',
  'minecraft:black_bed': 'Black Bed',
  // Flowers
  'minecraft:dandelion': 'Dandelion',
  'minecraft:poppy': 'Poppy',
  'minecraft:blue_orchid': 'Blue Orchid',
  'minecraft:allium': 'Allium',
  'minecraft:azure_bluet': 'Azure Bluet',
  'minecraft:red_tulip': 'Red Tulip',
  'minecraft:orange_tulip': 'Orange Tulip',
  'minecraft:white_tulip': 'White Tulip',
  'minecraft:pink_tulip': 'Pink Tulip',
  'minecraft:oxeye_daisy': 'Oxeye Daisy',
  'minecraft:cornflower': 'Cornflower',
  'minecraft:lily_of_the_valley': 'Lily of the Valley',
  'minecraft:wither_rose': 'Wither Rose',
  'minecraft:spore_blossom': 'Spore Blossom',
  'minecraft:big_dripleaf': 'Big Dripleaf',
  'minecraft:small_dripleaf': 'Small Dripleaf',
  'minecraft:pink_petals': 'Pink Petals',
  'minecraft:open_eyeblossom': 'Open Eyeblossom',
  'minecraft:closed_eyeblossom': 'Closed Eyeblossom',
  // Coral
  'minecraft:tube_coral': 'Tube Coral',
  'minecraft:brain_coral': 'Brain Coral',
  'minecraft:bubble_coral': 'Bubble Coral',
  'minecraft:fire_coral': 'Fire Coral',
  'minecraft:horn_coral': 'Horn Coral',
  'minecraft:dead_tube_coral': 'Dead Tube Coral',
  'minecraft:dead_brain_coral': 'Dead Brain Coral',
  'minecraft:dead_bubble_coral': 'Dead Bubble Coral',
  'minecraft:dead_fire_coral': 'Dead Fire Coral',
  'minecraft:dead_horn_coral': 'Dead Horn Coral',
  'minecraft:dead_tube_coral_block': 'Dead Tube Coral Block',
  'minecraft:dead_brain_coral_block': 'Dead Brain Coral Block',
  'minecraft:dead_bubble_coral_block': 'Dead Bubble Coral Block',
  'minecraft:dead_fire_coral_block': 'Dead Fire Coral Block',
  'minecraft:dead_horn_coral_block': 'Dead Horn Coral Block',
  'minecraft:dead_tube_coral_fan': 'Dead Tube Coral Fan',
  'minecraft:dead_fire_coral_fan': 'Dead Fire Coral Fan',
  // Terracotta
  'minecraft:terracotta': 'Terracotta',
  'minecraft:white_terracotta': 'White Terracotta',
  'minecraft:orange_terracotta': 'Orange Terracotta',
  'minecraft:magenta_terracotta': 'Magenta Terracotta',
  'minecraft:light_blue_terracotta': 'Light Blue Terracotta',
  'minecraft:yellow_terracotta': 'Yellow Terracotta',
  'minecraft:lime_terracotta': 'Lime Terracotta',
  'minecraft:pink_terracotta': 'Pink Terracotta',
  'minecraft:gray_terracotta': 'Gray Terracotta',
  'minecraft:light_gray_terracotta': 'Light Gray Terracotta',
  'minecraft:cyan_terracotta': 'Cyan Terracotta',
  'minecraft:purple_terracotta': 'Purple Terracotta',
  'minecraft:blue_terracotta': 'Blue Terracotta',
  'minecraft:brown_terracotta': 'Brown Terracotta',
  'minecraft:green_terracotta': 'Green Terracotta',
  'minecraft:red_terracotta': 'Red Terracotta',
  'minecraft:black_terracotta': 'Black Terracotta',
  'minecraft:white_glazed_terracotta': 'White Glazed Terracotta',
  'minecraft:orange_glazed_terracotta': 'Orange Glazed Terracotta',
  'minecraft:magenta_glazed_terracotta': 'Magenta Glazed Terracotta',
  'minecraft:light_blue_glazed_terracotta': 'Light Blue Glazed Terracotta',
  'minecraft:yellow_glazed_terracotta': 'Yellow Glazed Terracotta',
  'minecraft:lime_glazed_terracotta': 'Lime Glazed Terracotta',
  'minecraft:pink_glazed_terracotta': 'Pink Glazed Terracotta',
  'minecraft:gray_glazed_terracotta': 'Gray Glazed Terracotta',
  'minecraft:light_gray_glazed_terracotta': 'Light Gray Glazed Terracotta',
  'minecraft:cyan_glazed_terracotta': 'Cyan Glazed Terracotta',
  'minecraft:purple_glazed_terracotta': 'Purple Glazed Terracotta',
  'minecraft:blue_glazed_terracotta': 'Blue Glazed Terracotta',
  'minecraft:brown_glazed_terracotta': 'Brown Glazed Terracotta',
  'minecraft:green_glazed_terracotta': 'Green Glazed Terracotta',
  'minecraft:red_glazed_terracotta': 'Red Glazed Terracotta',
  'minecraft:black_glazed_terracotta': 'Black Glazed Terracotta',
  // Walls
  'minecraft:cobblestone_wall': 'Cobblestone Wall',
  'minecraft:mossy_cobblestone_wall': 'Mossy Cobblestone Wall',
  'minecraft:stone_brick_wall': 'Stone Brick Wall',
  'minecraft:mossy_stone_brick_wall': 'Mossy Stone Brick Wall',
  'minecraft:deepslate_brick_wall': 'Deepslate Brick Wall',
  'minecraft:deepslate_tile_wall': 'Deepslate Tile Wall',
  'minecraft:polished_deepslate_wall': 'Polished Deepslate Wall',
  'minecraft:cobbled_deepslate_wall': 'Cobbled Deepslate Wall',
  'minecraft:nether_brick_wall': 'Nether Brick Wall',
  'minecraft:red_nether_brick_wall': 'Red Nether Brick Wall',
  'minecraft:sandstone_wall': 'Sandstone Wall',
  'minecraft:red_sandstone_wall': 'Red Sandstone Wall',
  'minecraft:brick_wall': 'Brick Wall',
  'minecraft:prismarine_wall': 'Prismarine Wall',
  'minecraft:stone_wall': 'Stone Wall',
  // Stairs
  'minecraft:stone_brick_stairs': 'Stone Brick Stairs',
  'minecraft:cobblestone_stairs': 'Cobblestone Stairs',
  'minecraft:sandstone_stairs': 'Sandstone Stairs',
  'minecraft:red_sandstone_stairs': 'Red Sandstone Stairs',
  'minecraft:nether_brick_stairs': 'Nether Brick Stairs',
  'minecraft:quartz_stairs': 'Quartz Stairs',
  'minecraft:prismarine_stairs': 'Prismarine Stairs',
  'minecraft:dark_prismarine_stairs': 'Dark Prismarine Stairs',
  'minecraft:brick_stairs': 'Brick Stairs',
  'minecraft:purpur_stairs': 'Purpur Stairs',
  'minecraft:deepslate_brick_stairs': 'Deepslate Brick Stairs',
  'minecraft:deepslate_tile_stairs': 'Deepslate Tile Stairs',
  'minecraft:cobbled_deepslate_stairs': 'Cobbled Deepslate Stairs',
  'minecraft:polished_deepslate_stairs': 'Polished Deepslate Stairs',
  // Misc
  'minecraft:ender_chest': 'Ender Chest',
  'minecraft:chest': 'Chest',
  'minecraft:trapped_chest': 'Trapped Chest',
  'minecraft:barrel': 'Barrel',
  'minecraft:bundle': 'Bundle',
  'minecraft:goat_horn': 'Goat Horn',
  'minecraft:ominous_trial_key': 'Ominous Trial Key',
  'minecraft:trial_key': 'Trial Key',
  'minecraft:heavy_core': 'Heavy Core',
  'minecraft:breeze_rod': 'Breeze Rod',
  'minecraft:music_disc_13': 'Music Disc 13',
  'minecraft:music_disc_cat': 'Music Disc Cat',
  'minecraft:music_disc_blocks': 'Music Disc Blocks',
  'minecraft:music_disc_chirp': 'Music Disc Chirp',
  'minecraft:music_disc_far': 'Music Disc Far',
  'minecraft:music_disc_mall': 'Music Disc Mall',
  'minecraft:music_disc_mellohi': 'Music Disc Mellohi',
  'minecraft:music_disc_stal': 'Music Disc Stal',
  'minecraft:music_disc_strad': 'Music Disc Strad',
  'minecraft:music_disc_ward': 'Music Disc Ward',
  'minecraft:music_disc_11': 'Music Disc 11',
  'minecraft:music_disc_wait': 'Music Disc Wait',
  'minecraft:music_disc_otherside': 'Music Disc Otherside',
  'minecraft:music_disc_5': 'Music Disc 5',
  'minecraft:music_disc_pigstep': 'Music Disc Pigstep',
  'minecraft:music_disc_relic': 'Music Disc Relic',
  'minecraft:music_disc_creator': 'Music Disc Creator',
  'minecraft:music_disc_creator_music_box': 'Music Disc Creator Music Box',
  'minecraft:music_disc_lava_chicken': 'Music Disc Lava Chicken',
  'minecraft:writable_book': 'Writable Book',
  'minecraft:enchanted_book': 'Enchanted Book',
  'minecraft:netherite_upgrade_smithing_template': 'Netherite Upgrade Smithing Template',
  'minecraft:coast_armor_trim_smithing_template': 'Coast Armor Trim Smithing Template',
  'minecraft:dune_armor_trim_smithing_template': 'Dune Armor Trim Smithing Template',
  'minecraft:eye_armor_trim_smithing_template': 'Eye Armor Trim Smithing Template',
  'minecraft:raiser_armor_trim_smithing_template': 'Raiser Armor Trim Smithing Template',
  'minecraft:rib_armor_trim_smithing_template': 'Rib Armor Trim Smithing Template',
  'minecraft:sentry_armor_trim_smithing_template': 'Sentry Armor Trim Smithing Template',
  'minecraft:shaper_armor_trim_smithing_template': 'Shaper Armor Trim Smithing Template',
  'minecraft:silence_armor_trim_smithing_template': 'Silence Armor Trim Smithing Template',
  'minecraft:snout_armor_trim_smithing_template': 'Snout Armor Trim Smithing Template',
  'minecraft:tide_armor_trim_smithing_template': 'Tide Armor Trim Smithing Template',
  'minecraft:vex_armor_trim_smithing_template': 'Vex Armor Trim Smithing Template',
  'minecraft:ward_armor_trim_smithing_template': 'Ward Armor Trim Smithing Template',
  'minecraft:wayfinder_armor_trim_smithing_template': 'Wayfinder Armor Trim Smithing Template',
  'minecraft:cooked_beef': 'Cooked Beef',
  'minecraft:cooked_porkchop': 'Cooked Porkchop',
  'minecraft:cooked_mutton': 'Cooked Mutton',
  'minecraft:cooked_chicken': 'Cooked Chicken',
  'minecraft:cooked_rabbit': 'Cooked Rabbit',
  'minecraft:cooked_cod': 'Cooked Cod',
  'minecraft:cooked_salmon': 'Cooked Salmon',
  'minecraft:pufferfish': 'Pufferfish',
  'minecraft:tropical_fish': 'Tropical Fish',
  'minecraft:clay': 'Clay',
  'minecraft:pumpkin': 'Pumpkin',
  'minecraft:carved_pumpkin': 'Carved Pumpkin',
  'minecraft:jack_o_lantern': "Jack o'Lantern",
  'minecraft:deepslate_brick_slab': 'Deepslate Brick Slab',
  'minecraft:deepslate_tile_slab': 'Deepslate Tile Slab',
  'minecraft:cobbled_deepslate_slab': 'Cobbled Deepslate Slab',
  'minecraft:polished_deepslate_slab': 'Polished Deepslate Slab',
  'minecraft:crimson_roots': 'Crimson Roots',
  'minecraft:warped_roots': 'Warped Roots',
  'minecraft:twisting_vines': 'Twisting Vines',
  'minecraft:weeping_vines': 'Weeping Vines',
  'minecraft:nether_sprouts': 'Nether Sprouts',
  'minecraft:crimson_fungus': 'Crimson Fungus',
  'minecraft:warped_fungus': 'Warped Fungus',
  'minecraft:shroomlight': 'Shroomlight',
  'minecraft:brown_mushroom': 'Brown Mushroom',
  'minecraft:red_mushroom': 'Red Mushroom',
  'minecraft:warped_wart_block': 'Warped Wart Block',
  'minecraft:nether_wart': 'Nether Wart',
  'minecraft:beacon': 'Beacon',
  'minecraft:end_crystal': 'End Crystal',
  'minecraft:conduit': 'Conduit',
  'minecraft:respawn_anchor': 'Respawn Anchor',
  'minecraft:lodestone': 'Lodestone'
}

function resolveName(item) {
  if (item.display_name) return item.display_name
  return (
    ITEM_NAMES[item.id] ||
    item.id
      .replace('minecraft:', '')
      .replace(/_/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase())
  )
}

module.exports = { ITEM_NAMES, resolveName }
