// Every profitable crafting recipe on DonutSMP
// format: { result, resultCount, ingredients: [{item, count}], category, difficulty }
const RECIPES = [
  // === ENCHANTED BLOCKS (160 raw → 1 block) ===
  {result:'Enchanted Diamond Block',resultCount:1,ingredients:[{item:'Diamond',count:160}],category:'enchanted'},
  {result:'Enchanted Emerald Block',resultCount:1,ingredients:[{item:'Emerald',count:160}],category:'enchanted'},
  {result:'Enchanted Gold Block',resultCount:1,ingredients:[{item:'Gold Ingot',count:160}],category:'enchanted'},
  {result:'Enchanted Iron Block',resultCount:1,ingredients:[{item:'Iron Ingot',count:160}],category:'enchanted'},
  {result:'Enchanted Lapis Block',resultCount:1,ingredients:[{item:'Lapis Lazuli',count:160}],category:'enchanted'},
  {result:'Enchanted Redstone Block',resultCount:1,ingredients:[{item:'Redstone',count:160}],category:'enchanted'},
  {result:'Enchanted Coal Block',resultCount:1,ingredients:[{item:'Coal',count:160}],category:'enchanted'},
  {result:'Enchanted Nether Wart Block',resultCount:1,ingredients:[{item:'Nether Wart',count:160}],category:'enchanted'},
  {result:'Enchanted Quartz Block',resultCount:1,ingredients:[{item:'Quartz',count:160}],category:'enchanted'},
  {result:'Enchanted Glowstone Block',resultCount:1,ingredients:[{item:'Glowstone Dust',count:160}],category:'enchanted'},
  {result:'Enchanted Cactus Green Block',resultCount:1,ingredients:[{item:'Green Dye',count:160}],category:'enchanted'},
  {result:'Enchanted Cocoa Beans Block',resultCount:1,ingredients:[{item:'Cocoa Beans',count:160}],category:'enchanted'},
  {result:'Enchanted Sugar Cane Block',resultCount:1,ingredients:[{item:'Sugar Cane',count:160}],category:'enchanted'},
  {result:'Enchanted Bone Block',resultCount:1,ingredients:[{item:'Bone',count:160}],category:'enchanted'},
  {result:'Enchanted Feather Block',resultCount:1,ingredients:[{item:'Feather',count:160}],category:'enchanted'},
  {result:'Enchanted String Block',resultCount:1,ingredients:[{item:'String',count:160}],category:'enchanted'},
  {result:'Enchanted Gunpowder Block',resultCount:1,ingredients:[{item:'Gunpowder',count:160}],category:'enchanted'},
  {result:'Enchanted Slimeball Block',resultCount:1,ingredients:[{item:'Slimeball',count:160}],category:'enchanted'},
  {result:'Enchanted Ender Pearl Block',resultCount:1,ingredients:[{item:'Ender Pearl',count:160}],category:'enchanted'},
  {result:'Enchanted Blaze Powder Block',resultCount:1,ingredients:[{item:'Blaze Powder',count:160}],category:'enchanted'},
  {result:'Enchanted Ghast Tear Block',resultCount:1,ingredients:[{item:'Ghast Tear',count:160}],category:'enchanted'},
  {result:'Enchanted Magma Cream Block',resultCount:1,ingredients:[{item:'Magma Cream',count:160}],category:'enchanted'},
  {result:'Enchanted Spider Eye Block',resultCount:1,ingredients:[{item:'Spider Eye',count:160}],category:'enchanted'},
  {result:'Enchanted Leather Block',resultCount:1,ingredients:[{item:'Leather',count:160}],category:'enchanted'},
  {result:'Enchanted Clay Block',resultCount:1,ingredients:[{item:'Clay',count:160}],category:'enchanted'},
  {result:'Enchanted Oak Log Block',resultCount:1,ingredients:[{item:'Oak Log',count:160}],category:'enchanted'},
  {result:'Enchanted Spruce Log Block',resultCount:1,ingredients:[{item:'Spruce Log',count:160}],category:'enchanted'},
  {result:'Enchanted Birch Log Block',resultCount:1,ingredients:[{item:'Birch Log',count:160}],category:'enchanted'},
  {result:'Enchanted Jungle Log Block',resultCount:1,ingredients:[{item:'Jungle Log',count:160}],category:'enchanted'},
  {result:'Enchanted Acacia Log Block',resultCount:1,ingredients:[{item:'Acacia Log',count:160}],category:'enchanted'},
  {result:'Enchanted Dark Oak Log Block',resultCount:1,ingredients:[{item:'Dark Oak Log',count:160}],category:'enchanted'},
  {result:'Enchanted Pumpkin Block',resultCount:1,ingredients:[{item:'Pumpkin',count:160}],category:'enchanted'},
  {result:'Enchanted Melon Block',resultCount:1,ingredients:[{item:'Melon Slice',count:160}],category:'enchanted'},
  {result:'Enchanted Carrot Block',resultCount:1,ingredients:[{item:'Carrot',count:160}],category:'enchanted'},
  {result:'Enchanted Potato Block',resultCount:1,ingredients:[{item:'Potato',count:160}],category:'enchanted'},
  {result:'Enchanted Wheat Block',resultCount:1,ingredients:[{item:'Wheat',count:160}],category:'enchanted'},
  {result:'Enchanted Beetroot Block',resultCount:1,ingredients:[{item:'Beetroot',count:160}],category:'enchanted'},
  {result:'Enchanted Nether Star Block',resultCount:1,ingredients:[{item:'Nether Star',count:160}],category:'enchanted'},
  {result:'Enchanted Shulker Shell Block',resultCount:1,ingredients:[{item:'Shulker Shell',count:160}],category:'enchanted'},
  {result:'Enchanted Bottle o\' Enchanting Block',resultCount:1,ingredients:[{item:'Bottle o\' Enchanting',count:160}],category:'enchanted'},
  {result:'Enchanted Name Tag Block',resultCount:1,ingredients:[{item:'Name Tag',count:160}],category:'enchanted'},
  {result:'Enchanted Saddle Block',resultCount:1,ingredients:[{item:'Saddle',count:160}],category:'enchanted'},
  {result:'Enchanted Elixir Block',resultCount:1,ingredients:[{item:'Elixir',count:160}],category:'enchanted'},
  {result:'Enchanted Fossil Block',resultCount:1,ingredients:[{item:'Fossil',count:160}],category:'enchanted'},
  {result:'Enchanted Super Compactor 3000 Block',resultCount:1,ingredients:[{item:'Super Compactor 3000',count:160}],category:'enchanted'},
  {result:'Enchanted Hopper Block',resultCount:1,ingredients:[{item:'Hopper',count:160}],category:'enchanted'},
  {result:'Enchanted Compactor Block',resultCount:1,ingredients:[{item:'Compactor',count:160}],category:'enchanted'},
  {result:'Enchanted Enchantment Table Block',resultCount:1,ingredients:[{item:'Enchantment Table',count:160}],category:'enchanted'},
  {result:'Enchanted Anvil Block',resultCount:1,ingredients:[{item:'Anvil',count:160}],category:'enchanted'},
  {result:'Enchanted Grappling Hook Block',resultCount:1,ingredients:[{item:'Grappling Hook',count:160}],category:'enchanted'},
  {result:'Enchanted Aspect of the End Block',resultCount:1,ingredients:[{item:'Aspect of the End',count:160}],category:'enchanted'},
  {result:'Enchanted Book Block',resultCount:1,ingredients:[{item:'Enchanted Book',count:160}],category:'enchanted'},
  {result:'Enchanted Golden Apple Block',resultCount:1,ingredients:[{item:'Golden Apple',count:160}],category:'enchanted'},
  {result:'Enchanted Cookie Block',resultCount:1,ingredients:[{item:'Cookie',count:160}],category:'enchanted'},
  {result:'Enchanted Bread Block',resultCount:1,ingredients:[{item:'Bread',count:160}],category:'enchanted'},

  // === SMELTING / PROCESSING ===
  {result:'Iron Ingot',resultCount:1,ingredients:[{item:'Raw Iron',count:1}],category:'smelting'},
  {result:'Gold Ingot',resultCount:1,ingredients:[{item:'Raw Gold',count:1}],category:'smelting'},
  {result:'Copper Ingot',resultCount:1,ingredients:[{item:'Raw Copper',count:1}],category:'smelting'},
  {result:'Iron Ingot',resultCount:1,ingredients:[{item:'Iron Ore',count:1}],category:'smelting'},
  {result:'Gold Ingot',resultCount:1,ingredients:[{item:'Gold Ore',count:1}],category:'smelting'},
  {result:'Dried Kelp',resultCount:1,ingredients:[{item:'Kelp',count:1}],category:'smelting'},
  {result:'Glass',resultCount:1,ingredients:[{item:'Sand',count:1}],category:'smelting'},
  {result:'Smooth Stone',resultCount:1,ingredients:[{item:'Stone',count:1}],category:'smelting'},
  {result:'Smooth Sandstone',resultCount:1,ingredients:[{item:'Sandstone',count:1}],category:'smelting'},
  {result:'Smooth Red Sandstone',resultCount:1,ingredients:[{item:'Red Sandstone',count:1}],category:'smelting'},
  {result:'Smooth Quartz',resultCount:1,ingredients:[{item:'Quartz Block',count:1}],category:'smelting'},
  {result:'Smooth Quartz Slab',resultCount:2,ingredients:[{item:'Smooth Quartz',count:1}],category:'smelting'},
  {result:'Charcoal',resultCount:1,ingredients:[{item:'Oak Log',count:1}],category:'smelting'},
  {result:'Cooked Beef',resultCount:1,ingredients:[{item:'Beef',count:1}],category:'smelting'},
  {result:'Cooked Porkchop',resultCount:1,ingredients:[{item:'Porkchop',count:1}],category:'smelting'},
  {result:'Cooked Chicken',resultCount:1,ingredients:[{item:'Chicken',count:1}],category:'smelting'},
  {result:'Cooked Mutton',resultCount:1,ingredients:[{item:'Mutton',count:1}],category:'smelting'},
  {result:'Cooked Rabbit',resultCount:1,ingredients:[{item:'Rabbit',count:1}],category:'smelting'},
  {result:'Cooked Cod',resultCount:1,ingredients:[{item:'Cod',count:1}],category:'smelting'},
  {result:'Cooked Salmon',resultCount:1,ingredients:[{item:'Salmon',count:1}],category:'smelting'},
  {result:'Terracotta',resultCount:1,ingredients:[{item:'Clay',count:1}],category:'smelting'},
  {result:'Netherite Ingot',resultCount:1,ingredients:[{item:'Netherite Scrap',count:4}],category:'smithing'},

  // === WOOD PROCESSING (high volume, consistent) ===
  {result:'Oak Planks',resultCount:4,ingredients:[{item:'Oak Log',count:1}],category:'wood'},
  {result:'Spruce Planks',resultCount:4,ingredients:[{item:'Spruce Log',count:1}],category:'wood'},
  {result:'Birch Planks',resultCount:4,ingredients:[{item:'Birch Log',count:1}],category:'wood'},
  {result:'Jungle Planks',resultCount:4,ingredients:[{item:'Jungle Log',count:1}],category:'wood'},
  {result:'Acacia Planks',resultCount:4,ingredients:[{item:'Acacia Log',count:1}],category:'wood'},
  {result:'Dark Oak Planks',resultCount:4,ingredients:[{item:'Dark Oak Log',count:1}],category:'wood'},
  {result:'Stick',resultCount:4,ingredients:[{item:'Oak Planks',count:2}],category:'wood'},
  {result:'Crafting Table',resultCount:1,ingredients:[{item:'Oak Planks',count:4}],category:'wood'},
  {result:'Chest',resultCount:1,ingredients:[{item:'Oak Planks',count:8}],category:'wood'},
  {result:'Barrel',resultCount:1,ingredients:[{item:'Oak Planks',count:6},{item:'Oak Slab',count:2}],category:'wood'},
  {result:'Bookshelf',resultCount:1,ingredients:[{item:'Oak Planks',count:6},{item:'Book',count:3}],category:'wood'},
  {result:'Fence',resultCount:3,ingredients:[{item:'Oak Planks',count:4},{item:'Stick',count:2}],category:'wood'},
  {result:'Fence Gate',resultCount:1,ingredients:[{item:'Oak Planks',count:2},{item:'Stick',count:4}],category:'wood'},
  {result:'Sign',resultCount:3,ingredients:[{item:'Oak Planks',count:6},{item:'Stick',count:1}],category:'wood'},
  {result:'Boat',resultCount:1,ingredients:[{item:'Oak Planks',count:5}],category:'wood'},
  {result:'Trapdoor',resultCount:2,ingredients:[{item:'Oak Planks',count:6}],category:'wood'},
  {result:'Pressure Plate',resultCount:1,ingredients:[{item:'Oak Planks',count:2}],category:'wood'},
  {result:'Button',resultCount:1,ingredients:[{item:'Oak Planks',count:1}],category:'wood'},
  {result:'Ladder',resultCount:3,ingredients:[{item:'Stick',count:7}],category:'wood'},
  {result:'Cartography Table',resultCount:1,ingredients:[{item:'Paper',count:2},{item:'Oak Planks',count:4}],category:'wood'},
  {result:'Fletching Table',resultCount:1,ingredients:[{item:'Flint',count:2},{item:'Oak Planks',count:4}],category:'wood'},
  {result:'Loom',resultCount:1,ingredients:[{item:'String',count:2},{item:'Oak Planks',count:4}],category:'wood'},
  {result:'Composter',resultCount:1,ingredients:[{item:'Oak Slab',count:7}],category:'wood'},
  {result:'Stonecutter',resultCount:1,ingredients:[{item:'Iron Ingot',count:1},{item:'Stone',count:3}],category:'wood'},

  // === STONE CUTTING (builders drive demand) ===
  {result:'Stone Bricks',resultCount:4,ingredients:[{item:'Stone',count:4}],category:'stone'},
  {result:'Chiseled Stone Bricks',resultCount:1,ingredients:[{item:'Stone Brick Slab',count:2}],category:'stone'},
  {result:'Stone Brick Stairs',resultCount:4,ingredients:[{item:'Stone Bricks',count:6}],category:'stone'},
  {result:'Stone Brick Slab',resultCount:6,ingredients:[{item:'Stone Bricks',count:3}],category:'stone'},
  {result:'Stone Brick Wall',resultCount:6,ingredients:[{item:'Stone Bricks',count:6}],category:'stone'},
  {result:'Chiseled Sandstone',resultCount:1,ingredients:[{item:'Sandstone Slab',count:2}],category:'stone'},
  {result:'Smooth Sandstone Slab',resultCount:2,ingredients:[{item:'Smooth Sandstone',count:1}],category:'stone'},
  {result:'Cut Sandstone',resultCount:4,ingredients:[{item:'Sandstone',count:4}],category:'stone'},
  {result:'Cut Red Sandstone',resultCount:4,ingredients:[{item:'Red Sandstone',count:4}],category:'stone'},
  {result:'Polished Deepslate',resultCount:4,ingredients:[{item:'Cobbled Deepslate',count:4}],category:'stone'},
  {result:'Deepslate Bricks',resultCount:4,ingredients:[{item:'Deepslate',count:4}],category:'stone'},
  {result:'Deepslate Tiles',resultCount:4,ingredients:[{item:'Deepslate Bricks',count:4}],category:'stone'},
  {result:'Chiseled Deepslate',resultCount:1,ingredients:[{item:'Deepslate Tile Slab',count:2}],category:'stone'},
  {result:'Cobbled Deepslate Stairs',resultCount:4,ingredients:[{item:'Cobbled Deepslate',count:6}],category:'stone'},
  {result:'Cobbled Deepslate Slab',resultCount:6,ingredients:[{item:'Cobbled Deepslate',count:3}],category:'stone'},
  {result:'Cobbled Deepslate Wall',resultCount:6,ingredients:[{item:'Cobbled Deepslate',count:6}],category:'stone'},
  {result:'Deepslate Brick Stairs',resultCount:4,ingredients:[{item:'Deepslate Bricks',count:6}],category:'stone'},
  {result:'Deepslate Brick Slab',resultCount:6,ingredients:[{item:'Deepslate Bricks',count:3}],category:'stone'},
  {result:'Deepslate Tile Stairs',resultCount:4,ingredients:[{item:'Deepslate Tiles',count:6}],category:'stone'},
  {result:'Deepslate Tile Slab',resultCount:6,ingredients:[{item:'Deepslate Tiles',count:3}],category:'stone'},
  {result:'Nether Bricks',resultCount:4,ingredients:[{item:'Netherrack',count:4}],category:'stone'},
  {result:'Red Nether Bricks',resultCount:4,ingredients:[{item:'Nether Brick',count:4},{item:'Nether Wart',count:4}],category:'stone'},
  {result:'Purpur Block',resultCount:4,ingredients:[{item:'Popped Chorus Fruit',count:4}],category:'stone'},
  {result:'Prismarine',resultCount:4,ingredients:[{item:'Prismarine Shard',count:4}],category:'stone'},
  {result:'Prismarine Bricks',resultCount:4,ingredients:[{item:'Prismarine Shard',count:6}],category:'stone'},
  {result:'Dark Prismarine',resultCount:4,ingredients:[{item:'Prismarine Shard',count:6},{item:'Ink Sac',count:1}],category:'stone'},
  {result:'Prismarine Bricks Slab',resultCount:6,ingredients:[{item:'Prismarine Bricks',count:3}],category:'stone'},
  {result:'Dark Prismarine Slab',resultCount:6,ingredients:[{item:'Dark Prismarine',count:3}],category:'stone'},
  {result:'Prismarine Stairs',resultCount:4,ingredients:[{item:'Prismarine',count:6}],category:'stone'},
  {result:'Prismarine Brick Stairs',resultCount:4,ingredients:[{item:'Prismarine Bricks',count:6}],category:'stone'},
  {result:'Dark Prismarine Stairs',resultCount:4,ingredients:[{item:'Dark Prismarine',count:6}],category:'stone'},
  {result:'End Stone Bricks',resultCount:4,ingredients:[{item:'End Stone',count:4}],category:'stone'},

  // === REDSTONE COMPONENTS (deep ingredient chains) ===
  {result:'Redstone Repeater',resultCount:1,ingredients:[{item:'Redstone',count:3},{item:'Redstone Torch',count:2},{item:'Stone',count:3}],category:'redstone'},
  {result:'Redstone Comparator',resultCount:1,ingredients:[{item:'Redstone Torch',count:3},{item:'Stone',count:3},{item:'Nether Quartz',count:1}],category:'redstone'},
  {result:'Piston',resultCount:1,ingredients:[{item:'Oak Planks',count:4},{item:'Cobblestone',count:3},{item:'Iron Ingot',count:1},{item:'Redstone',count:1}],category:'redstone'},
  {result:'Sticky Piston',resultCount:1,ingredients:[{item:'Slimeball',count:1},{item:'Piston',count:1}],category:'redstone'},
  {result:'Hopper',resultCount:1,ingredients:[{item:'Iron Ingot',count:5},{item:'Chest',count:1}],category:'redstone'},
  {result:'Dropper',resultCount:1,ingredients:[{item:'Cobblestone',count:7},{item:'Redstone',count:1}],category:'redstone'},
  {result:'Dispenser',resultCount:1,ingredients:[{item:'Cobblestone',count:7},{item:'Redstone',count:1},{item:'Bow',count:1}],category:'redstone'},
  {result:'Observer',resultCount:1,ingredients:[{item:'Cobblestone',count:6},{item:'Redstone',count:2},{item:'Nether Quartz',count:1}],category:'redstone'},
  {result:'Daylight Detector',resultCount:1,ingredients:[{item:'Glass',count:3},{item:'Nether Quartz',count:3},{item:'Oak Slab',count:3}],category:'redstone'},
  {result:'Redstone Lamp',resultCount:1,ingredients:[{item:'Redstone',count:4},{item:'Glowstone',count:1}],category:'redstone'},
  {result:'Target',resultCount:1,ingredients:[{item:'Redstone',count:4},{item:'Hay Bale',count:1}],category:'redstone'},
  {result:'Note Block',resultCount:1,ingredients:[{item:'Oak Planks',count:8},{item:'Redstone',count:1}],category:'redstone'},
  {result:'Lever',resultCount:1,ingredients:[{item:'Cobblestone',count:1},{item:'Stick',count:1}],category:'redstone'},
  {result:'Stone Pressure Plate',resultCount:1,ingredients:[{item:'Stone',count:2}],category:'redstone'},
  {result:'Weighted Pressure Plate (Light)',resultCount:1,ingredients:[{item:'Gold Ingot',count:2}],category:'redstone'},
  {result:'Weighted Pressure Plate (Heavy)',resultCount:1,ingredients:[{item:'Iron Ingot',count:2}],category:'redstone'},
  {result:'Tripwire Hook',resultCount:2,ingredients:[{item:'Stick',count:2},{item:'Iron Ingot',count:1},{item:'String',count:1}],category:'redstone'},
  {result:'TNT',resultCount:1,ingredients:[{item:'Gunpowder',count:5},{item:'Sand',count:4}],category:'redstone'},

  // === NETHER MATERIALS (volatile, high value) ===
  {result:'Blaze Powder',resultCount:2,ingredients:[{item:'Blaze Rod',count:1}],category:'nether'},
  {result:'Magma Cream',resultCount:1,ingredients:[{item:'Slimeball',count:1},{item:'Blaze Powder',count:1}],category:'nether'},
  {result:'End Crystal',resultCount:1,ingredients:[{item:'Eye of Ender',count:1},{item:'Ghast Tear',count:1},{item:'Glass',count:7}],category:'nether'},
  {result:'Eye of Ender',resultCount:1,ingredients:[{item:'Blaze Powder',count:1},{item:'Ender Pearl',count:1}],category:'nether'},
  {result:'Fermented Spider Eye',resultCount:1,ingredients:[{item:'Spider Eye',count:1},{item:'Sugar',count:1},{item:'Brown Mushroom',count:1}],category:'nether'},
  {result:'Enchantment Table',resultCount:1,ingredients:[{item:'Diamond',count:2},{item:'Obsidian',count:4},{item:'Book',count:1}],category:'nether'},
  {result:'Anvil',resultCount:1,ingredients:[{item:'Iron Block',count:3},{item:'Iron Ingot',count:4}],category:'nether'},
  {result:'Ender Chest',resultCount:1,ingredients:[{item:'Obsidian',count:8},{item:'Eye of Ender',count:1}],category:'nether'},
  {respawn_anchor:'Respawn Anchor',resultCount:1,ingredients:[{item:'Crying Obsidian',count:6},{item:'Glowstone',count:3}],category:'nether'},
  {result:'Netherite Upgrade Smithing Template',resultCount:1,ingredients:[{item:'Netherrack',count:7},{item:'Diamond',count:1}],category:'nether'},
  {result:'Beacon',resultCount:1,ingredients:[{item:'Glass',count:5},{item:'Nether Star',count:1},{item:'Obsidian',count:3}],category:'nether'},
  {result:'Conduit',resultCount:1,ingredients:[{item:'Nautilus Shell',count:4},{item:'Heart of the Sea',count:1}],category:'nether'},

  // === TOOLS & WEAPONS ===
  {result:'Iron Sword',resultCount:1,ingredients:[{item:'Iron Ingot',count:2},{item:'Stick',count:1}],category:'tools'},
  {result:'Iron Pickaxe',resultCount:1,ingredients:[{item:'Iron Ingot',count:3},{item:'Stick',count:2}],category:'tools'},
  {result:'Iron Axe',resultCount:1,ingredients:[{item:'Iron Ingot',count:3},{item:'Stick',count:2}],category:'tools'},
  {result:'Iron Shovel',resultCount:1,ingredients:[{item:'Iron Ingot',count:1},{item:'Stick',count:2}],category:'tools'},
  {result:'Iron Hoe',resultCount:1,ingredients:[{item:'Iron Ingot',count:2},{item:'Stick',count:2}],category:'tools'},
  {result:'Diamond Sword',resultCount:1,ingredients:[{item:'Diamond',count:2},{item:'Stick',count:1}],category:'tools'},
  {result:'Diamond Pickaxe',resultCount:1,ingredients:[{item:'Diamond',count:3},{item:'Stick',count:2}],category:'tools'},
  {result:'Diamond Axe',resultCount:1,ingredients:[{item:'Diamond',count:3},{item:'Stick',count:2}],category:'tools'},
  {result:'Diamond Shovel',resultCount:1,ingredients:[{item:'Diamond',count:1},{item:'Stick',count:2}],category:'tools'},
  {result:'Diamond Hoe',resultCount:1,ingredients:[{item:'Diamond',count:2},{item:'Stick',count:2}],category:'tools'},
  {result:'Netherite Sword',resultCount:1,ingredients:[{item:'Netherite Ingot',count:2},{item:'Stick',count:1}],category:'tools'},
  {result:'Netherite Pickaxe',resultCount:1,ingredients:[{item:'Netherite Ingot',count:3},{item:'Stick',count:2}],category:'tools'},
  {result:'Netherite Axe',resultCount:1,ingredients:[{item:'Netherite Ingot',count:3},{item:'Stick',count:2}],category:'tools'},
  {result:'Netherite Shovel',resultCount:1,ingredients:[{item:'Netherite Ingot',count:1},{item:'Stick',count:2}],category:'tools'},
  {result:'Netherite Hoe',resultCount:1,ingredients:[{item:'Netherite Ingot',count:2},{item:'Stick',count:2}],category:'tools'},
  {result:'Bow',resultCount:1,ingredients:[{item:'Stick',count:3},{item:'String',count:3}],category:'tools'},
  {result:'Crossbow',resultCount:1,ingredients:[{item:'Stick',count:3},{item:'Iron Ingot',count:1},{item:'String',count:2}],category:'tools'},
  {result:'Shears',resultCount:1,ingredients:[{item:'Iron Ingot',count:2}],category:'tools'},
  {result:'Shield',resultCount:1,ingredients:[{item:'Oak Planks',count:6},{item:'Iron Ingot',count:1}],category:'tools'},
  {result:'Flint and Steel',resultCount:1,ingredients:[{item:'Flint',count:1},{item:'Iron Ingot',count:1}],category:'tools'},
  {result:'Fishing Rod',resultCount:1,ingredients:[{item:'Stick',count:3},{item:'String',count:2}],category:'tools'},
  {result:'Clock',resultCount:1,ingredients:[{item:'Gold Ingot',count:4},{item:'Redstone',count:1}],category:'tools'},
  {result:'Compass',resultCount:1,ingredients:[{item:'Iron Ingot',count:4},{item:'Redstone',count:1}],category:'tools'},
  {result:'Spyglass',resultCount:1,ingredients:[{item:'Copper Ingot',count:2},{item:'Amethyst Shard',count:1}],category:'tools'},
  {result:'Lead',resultCount:2,ingredients:[{item:'String',count:4},{item:'Slimeball',count:1}],category:'tools'},

  // === ARMOR ===
  {result:'Iron Helmet',resultCount:1,ingredients:[{item:'Iron Ingot',count:5}],category:'armor'},
  {result:'Iron Chestplate',resultCount:1,ingredients:[{item:'Iron Ingot',count:8}],category:'armor'},
  {result:'Iron Leggings',resultCount:1,ingredients:[{item:'Iron Ingot',count:7}],category:'armor'},
  {result:'Iron Boots',resultCount:1,ingredients:[{item:'Iron Ingot',count:4}],category:'armor'},
  {result:'Diamond Helmet',resultCount:1,ingredients:[{item:'Diamond',count:5}],category:'armor'},
  {result:'Diamond Chestplate',resultCount:1,ingredients:[{item:'Diamond',count:8}],category:'armor'},
  {result:'Diamond Leggings',resultCount:1,ingredients:[{item:'Diamond',count:7}],category:'armor'},
  {result:'Diamond Boots',resultCount:1,ingredients:[{item:'Diamond',count:4}],category:'armor'},
  {result:'Netherite Helmet',resultCount:1,ingredients:[{item:'Netherite Ingot',count:5}],category:'armor'},
  {result:'Netherite Chestplate',resultCount:1,ingredients:[{item:'Netherite Ingot',count:8}],category:'armor'},
  {result:'Netherite Leggings',resultCount:1,ingredients:[{item:'Netherite Ingot',count:7}],category:'armor'},
  {result:'Netherite Boots',resultCount:1,ingredients:[{item:'Netherite Ingot',count:4}],category:'armor'},
  {result:'Turtle Helmet',resultCount:1,ingredients:[{item:'Scute',count:5}],category:'armor'},

  // === DYE COMBINATIONS ===
  {result:'Orange Dye',resultCount:2,ingredients:[{item:'Red Dye',count:1},{item:'Yellow Dye',count:1}],category:'dye'},
  {result:'Lime Dye',resultCount:2,ingredients:[{item:'Green Dye',count:1},{item:'White Dye',count:1}],category:'dye'},
  {result:'Light Blue Dye',resultCount:2,ingredients:[{item:'Blue Dye',count:1},{item:'White Dye',count:1}],category:'dye'},
  {result:'Purple Dye',resultCount:2,ingredients:[{item:'Blue Dye',count:1},{item:'Red Dye',count:1}],category:'dye'},
  {result:'Cyan Dye',resultCount:2,ingredients:[{item:'Blue Dye',count:1},{item:'Green Dye',count:1}],category:'dye'},
  {result:'Magenta Dye',resultCount:2,ingredients:[{item:'Purple Dye',count:1},{item:'Pink Dye',count:1}],category:'dye'},
  {result:'Brown Dye',resultCount:1,ingredients:[{item:'Cocoa Beans',count:1}],category:'dye'},

  // === BLOCK COMPRESSION ===
  {result:'Iron Block',resultCount:1,ingredients:[{item:'Iron Ingot',count:9}],category:'compression'},
  {result:'Gold Block',resultCount:1,ingredients:[{item:'Gold Ingot',count:9}],category:'compression'},
  {result:'Diamond Block',resultCount:1,ingredients:[{item:'Diamond',count:9}],category:'compression'},
  {result:'Emerald Block',resultCount:1,ingredients:[{item:'Emerald',count:9}],category:'compression'},
  {result:'Lapis Block',resultCount:1,ingredients:[{item:'Lapis Lazuli',count:9}],category:'compression'},
  {result:'Redstone Block',resultCount:1,ingredients:[{item:'Redstone',count:9}],category:'compression'},
  {result:'Coal Block',resultCount:1,ingredients:[{item:'Coal',count:9}],category:'compression'},
  {result:'Copper Block',resultCount:1,ingredients:[{item:'Copper Ingot',count:9}],category:'compression'},
  {result:'Dried Kelp Block',resultCount:1,ingredients:[{item:'Dried Kelp',count:9}],category:'compression'},
  {result:'Honeycomb Block',resultCount:1,ingredients:[{item:'Honeycomb',count:9}],category:'compression'},
  {result:'Snow Block',resultCount:1,ingredients:[{item:'Snowball',count:4}],category:'compression'},
  {result:'Packed Ice',resultCount:1,ingredients:[{item:'Ice',count:9}],category:'compression'},
  {result:'Blue Ice',resultCount:1,ingredients:[{item:'Packed Ice',count:9}],category:'compression'},
  {result:'Quartz Block',resultCount:1,ingredients:[{item:'Nether Quartz',count:4}],category:'compression'},
  {result:'Glowstone',resultCount:1,ingredients:[{item:'Glowstone Dust',count:4}],category:'compression'},
  {result:'Hay Bale',resultCount:1,ingredients:[{item:'Wheat',count:9}],category:'compression'},
  {result:'Slime Block',resultCount:1,ingredients:[{item:'Slimeball',count:9}],category:'compression'},

  // === FOOD & FARMING ===
  {result:'Bread',resultCount:1,ingredients:[{item:'Wheat',count:3}],category:'food'},
  {result:'Golden Carrot',resultCount:1,ingredients:[{item:'Carrot',count:1},{item:'Gold Nugget',count:8}],category:'food'},
  {result:'Golden Apple',resultCount:1,ingredients:[{item:'Apple',count:1},{item:'Gold Nugget',count:8}],category:'food'},
  {result:'Cookie',resultCount:8,ingredients:[{item:'Wheat',count:2},{item:'Cocoa Beans',count:2}],category:'food'},
  {result:'Cake',resultCount:1,ingredients:[{item:'Wheat',count:3},{item:'Sugar',count:2},{item:'Egg',count:1},{item:'Milk Bucket',count:3}],category:'food'},
  {result:'Pumpkin Pie',resultCount:1,ingredients:[{item:'Pumpkin',count:1},{item:'Sugar',count:1},{item:'Egg',count:1}],category:'food'},
  {result:'Mushroom Stew',resultCount:1,ingredients:[{item:'Bowl',count:1},{item:'Red Mushroom',count:1},{item:'Brown Mushroom',count:1}],category:'food'},
  {result:'Beetroot Soup',resultCount:1,ingredients:[{item:'Bowl',count:1},{item:'Beetroot',count:3}],category:'food'},
  {result:'Sugar',resultCount:1,ingredients:[{item:'Sugar Cane',count:1}],category:'food'},
  {result:'Paper',resultCount:3,ingredients:[{item:'Sugar Cane',count:3}],category:'food'},
  {result:'Book',resultCount:1,ingredients:[{item:'Paper',count:3},{item:'Leather',count:1}],category:'food'},
  {result:'Enchanted Book',resultCount:1,ingredients:[{item:'Book',count:1}],category:'food'},

  // === SHULKER BOX CRAFTING ===
  {result:'Shulker Box',resultCount:1,ingredients:[{item:'Shulker Shell',count:2},{item:'Chest',count:1}],category:'shulker'},
  {result:'White Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'White Dye',count:1}],category:'shulker'},
  {result:'Orange Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Orange Dye',count:1}],category:'shulker'},
  {result:'Magenta Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Magenta Dye',count:1}],category:'shulker'},
  {result:'Light Blue Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Light Blue Dye',count:1}],category:'shulker'},
  {result:'Yellow Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Yellow Dye',count:1}],category:'shulker'},
  {result:'Lime Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Lime Dye',count:1}],category:'shulker'},
  {result:'Pink Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Pink Dye',count:1}],category:'shulker'},
  {result:'Gray Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Gray Dye',count:1}],category:'shulker'},
  {result:'Light Gray Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Light Gray Dye',count:1}],category:'shulker'},
  {result:'Cyan Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Cyan Dye',count:1}],category:'shulker'},
  {result:'Purple Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Purple Dye',count:1}],category:'shulker'},
  {result:'Blue Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Blue Dye',count:1}],category:'shulker'},
  {result:'Brown Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Brown Dye',count:1}],category:'shulker'},
  {result:'Green Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Green Dye',count:1}],category:'shulker'},
  {result:'Red Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Red Dye',count:1}],category:'shulker'},
  {result:'Black Shulker Box',resultCount:1,ingredients:[{item:'Shulker Box',count:1},{item:'Black Dye',count:1}],category:'shulker'},
];

module.exports = RECIPES;
